Preco_Garrafa= float(input("Digite o preço da garrafa: "))
Preco_tampa= float(input("Digite o preço da tampa: "))
Preco_Rotulo= float(input("Digite o preço do rótulo: "))
Preco_Lacre= float(input("Digite o preço do lácre: "))
Preco_Cola= float(input("Digite o preço da cola: "))
Gastos_diversos= float(input("Digite outros gastos: "))
Mao_de_obra= float(input("Digite o quanto você gasta de mão de obra: "))
valor_produto= (Preco_Cola+Preco_Garrafa+Preco_Lacre+Preco_Rotulo+Preco_tampa+Gastos_diversos+Mao_de_obra)
irpj= float(input("Digite a quantidade de impostos que você paga: "))
lucro= float(input("Digite em porcentagem quanto você quer de lucro: "))
impostos=(irpj+lucro)
valor_do_impostos= ((100-impostos)/100)
Preco_de_venda=(valor_produto/valor_do_impostos)
print(Preco_de_venda)